.TH "Node< T >" 3 "SLL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node< T > \- A class representing node\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <classes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.RI "A default constructor\&. "
.ti -1c
.RI "\fBNode\fP (T \fBdata\fP)"
.br
.RI "A constructor\&. "
.ti -1c
.RI "\fB~Node\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBdata\fP"
.br
.RI "Variable which holds data stored in the node\&. "
.ti -1c
.RI "std::shared_ptr< \fBNode\fP< T > > \fBnext\fP"
.br
.RI "Pointer to another node\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class Node< T >"A class representing node\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBNode\fP< T >\fB::Node\fP (T data)\fR [inline]\fP"

.PP
A constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP information to be stored in the node\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SLL from the source code\&.
